#!/usr/bin/env bash
# Install nginx on web-01 server
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# It must return a page that contains the string Hello World!

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed i 's/.*/Hello world/' /var/www/html/index.html
sudo service nginx restart
