#!/usr/bin/env bash
# creates a compressed archive after generating MYSQL dump
if [ $# -eq 0 ]; then
    exit 1
fi 

backup_file="backup.sql"
compressed_file="$(date +%d-%m-%Y).tar.gz"

mysqldump -u root -p"$1" --all-databases > "$backup_file"
tar -czvf "$compressed_file" "$backup_file"
rm "$backup_file"
