#!/usr/bin/env bash
# a while loop with an if statement where "Best School" then "hi" are displayed

number=1
while [ $number -le 10 ]; do 
        echo "Best School" 
	        if [ $number == 9 ] 
		then echo "Hi"
	fi
        number=$(( number + 1 ))
done
