#!/usr/bin/env bash
# displays:The content of the current directory
# In a list format, Where only the part of the name after the first dash is displayed

for file in *
do
    if [[ $file == .* ]]; then
        continue
    fi

    name=${file#*-}

    echo "$name"
done
