#!/usr/bin/env bash
# nginx as nginx non-root user
usermod -u 1000 nginx
chown -R nginx:nginx /var/cache/nginx/
sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/' /etc/nginx/nginx.conf
service nginx restart
